apiVersion: v1
kind: Pod
metadata:
  name: app2
  namespace: my-namespace
  labels:
    app: demoapp2

spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
      - containerPort: 80